*Python'da veri tipleri* aşağıdaki gibiyken;
dizeler - metin verilerini temsil etmek için kullanılır, metin tırnak işaretleri altında verilir. örn. "ABCD"

integer - tam sayıları temsil etmek için kullanılır. örn. -1, -2, -3

float - gerçek sayıları temsil etmek için kullanılır. örn. 1.2, 42.42

boolean - True veya False'u temsil etmek için kullanılır.

complex - karmaşık sayıları temsil etmek için kullanılır. örn. 1.0 + 2.0j, 1.5 + 2.5j

*Numpy'da veri tipleri* biraz daha karmaşıktır. Gelin açıklayalım.

i - tamsayı

b - boolean

u - işaretsiz tamsayı

f - float

c - karmaşık float

m - timedelta

M - datetime

O - nesne

S - dize

U - unicode dize

V - diğer tür için sabit bellek parçası ( void )

In [1]:
import numpy as np

Dizinin veri türünü kontrol etme

In [2]:
arr = np.array([1, 2, 3, 4])

print(arr.dtype)

int32


In [3]:
arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype)

<U6


In [7]:
arr = np.array([1, 2, 3, 4], dtype='f')

print(arr.dtype)
print(arr)

float32
[1. 2. 3. 4.]


In [8]:
arr = np.array([1, 2, 3, 4], dtype='U')

print(arr.dtype)
print(arr)


<U1
['1' '2' '3' '4']


In [9]:
arr = np.array([1, 2, 3, 4], dtype='f8')

print(arr.dtype)
print(arr)

float64
[1. 2. 3. 4.]


In [10]:
arr = np.array([1, 2, 3, 4], dtype='i8')

print(arr.dtype)
print(arr)

int64
[1 2 3 4]


In [13]:
arr = np.array([1, 2, 3, 4], dtype='U')

print(arr.dtype)
print(arr)

<U1
['1' '2' '3' '4']


In [14]:
arr = np.array([1, 2, 3, 4], dtype='S')

print(arr.dtype)
print(arr)

|S1
[b'1' b'2' b'3' b'4']


In [15]:
arr = np.array([1, 2, 3, 4], dtype='O')

print(arr.dtype) 
print(arr)

object
[1 2 3 4]


In [17]:
arr = np.array([1, 2, 3, 4], dtype='i4')

print(arr.dtype)  
print(arr)

int32
[1 2 3 4]


In [18]:
arr = np.array([1, 2, 3, 4], dtype='c8')

print(arr.dtype)
print(arr)

complex64
[1.+0.j 2.+0.j 3.+0.j 4.+0.j]


In [19]:
arr = np.array([1, 2, 3, 4], dtype='m')

print(arr.dtype)
print(arr)

timedelta64
[1 2 3 4]


In [20]:
arr = np.array([1, 2, 3, 4], dtype='f8')

print(arr.dtype)
print(arr)

float64
[1. 2. 3. 4.]
