Bu dosyada numpyda dizi işlemleri yapılırken spesifik bir elemana veya elemanlara ulaşma çalışmaları yapacağız.

Dizi indeksleme, bir dizi öğesine erişimle aynıdır.

Bir dizi öğesine, dizin numarasına başvurarak erişebilirsiniz.

NumPy dizilerindeki dizinler 0 ile başlar, yani ilk öğenin dizini 0, ikinci öğenin dizini 1 vb.'dir.

In [1]:
import numpy as np

In [3]:
arr = np.array([1, 2, 3, 4, 5])

print(arr[0])

1


In [5]:
#Birden fazla boyutlu dizilerde, dizinleme için birden fazla indeks kullanılabilir.

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('2nci dizinin 1nci elemanı :', arr[1, 1])
print('1nci dizinin 3nci elemanı :', arr[0, 3])
print('2nci dizinin 4nci elemanı :', arr[1, 4])

2nci dizinin 1nci elemanı : 7
1nci dizinin 3nci elemanı : 4
2nci dizinin 4nci elemanı : 10


In [6]:
#Negatif indeksleme

arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])

print('Son eleman :', arr[-1, -1])


Son eleman : 10


*Slicing*

Python'da dilimleme, elemanları verilen bir indeksten verilen başka bir indekse taşımak anlamına gelir.

Dizin yerine dilimi şu şekilde geçiririz: [başlangıç:bitiş].

Adımı da şu şekilde tanımlayabiliriz: [başlangıç:bitiş:adım]

NOT: Başlangıç adımı dahilken, bitiş adımı dahil değildir.

In [8]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[1:5])

[2 3 4 5]


In [15]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print("4ncü elemandan sonuna kadar :", arr[4:])

4ncü elemandan sonuna kadar : [5 6 7]


In [16]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print("1nci elemandan 4ncü elemana kadar :", arr[:4])

1nci elemandan 4ncü elemana kadar : [1 2 3 4]


In [10]:
#Slicing 2-D Diziler

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print("2nci dizinin 1nci elemanından 4ncü elemanına kadar :", arr[1, 1:4])


2nci dizinin 1nci elemanından 4ncü elemanına kadar : [7 8 9]


In [11]:
#Slicing 3-D Diziler

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print("1nci dizinin 2nci dizinin 3ncü elemanı :", arr[0, 1, 2])

1nci dizinin 2nci dizinin 3ncü elemanı : 6


In [12]:
#Slicing ile Dizileri Değiştirme

arr = np.array([1, 2, 3, 4, 5])

arr[1:3] = [99, 99]

print(arr)

[ 1 99 99  4  5]


In [13]:
#Slicing ile Dizileri Kopyalama

arr = np.array([1, 2, 3, 4, 5])

arr_copy = arr[0:3].copy()

print(arr_copy)

[1 2 3]


In [14]:
#Slicing ile Dizileri Kopyalama

arr = np.array([1, 2, 3, 4, 5])

arr_copy = arr[0:3].copy()

print(arr_copy) 

[1 2 3]


In [17]:
#Negatif Slicing
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print("3ncü elemandan 5nci elemana kadar :", arr[-3:-1])

3ncü elemandan 5nci elemana kadar : [5 6]
