*NUMPY*

'Numerical python' olarak kısaltılan Numpy dizilerle sayısal işlemler yapan bir python kütüphanesidir. Ayrıca doğrusal cebir, fourier dönüşümü ve matrisler alanında çalışmaya yönelik fonksiyonları da bulunur.

In [2]:
#Numpy'ı import etmek ve çalışmalarda kısaltarak kullanmak için
import numpy as np

*Listlerden Dizi Oluşturmak*

In [3]:
arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


*0-D Diziler*

In [4]:
arr = np.array(40)

print(arr)

40


*1-D Diziler*

In [5]:
arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


*2-D Diziler*

In [6]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr)

[[1 2 3]
 [4 5 6]]


*3-D Diziler*

In [7]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr)


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


*Dizilerin Boyut Sayısını Kontrol Etme*

NumPy Dizileri, dizinin kaç boyutlu olduğunu belirten bir tam sayı döndüren ndim niteliğini sağlar.

In [8]:
a = np.array(40)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


*Daha Fazla Boyutlu Dizi Oluşturma*

Bunun için 'ndim' parametresini kullanabilirsiniz.

In [9]:
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions : 5
